# Generated by Django 4.2.4 on 2023-08-09 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eattag',
            name='eat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eats.eat'),
        ),
        migrations.AddField(
            model_name='eattag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eats.tag'),
        ),
        migrations.AddField(
            model_name='eatimage',
            name='eat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eats.eat'),
        ),
        migrations.AddField(
            model_name='eat',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eats.place'),
        ),
        migrations.AddField(
            model_name='eat',
            name='tags',
            field=models.ManyToManyField(through='eats.EatTag', to='eats.tag'),
        ),
        migrations.AddField(
            model_name='eat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eattag',
            constraint=models.UniqueConstraint(fields=('eat', 'tag'), name='unique_tag_per_eat'),
        ),
    ]
